### ISSUE TITLE
Port codes for visualizing commercial catch

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/CA_quillback_rockfish_2025#13]
There are a suite of port codes within the PacFIN fish ticket data. For california, @melissamonk-NOAA tells me that catch expansions are based on gear groups and port groups. Thus, to visualize catches across gears or ports, we should use the gear group or port group codes as opposed to the individual gear or port codes.  I have a good sense of what pacfin field names to use for gear (PACFIN_GROUP_GEAR_CODE), but for port its less clear. 

There are two fields that could represent port grouping IOPAC_PORT_GROUP and PACFIN_GROUP_PORT_CODE. These two line up well but not perfectly. PACFIN_GROUP_PORT_CODE has fewer NA's so Im inclined to use that one. @EJDick-NOAA do you have a sense for which to use?

**Comment by EJDick-NOAA** [comment]
@brianlangseth-NOAA It would help if I knew what question you're trying to answer. Species compositions for California are estimated using 6 strata: Market Category, Year, Quarter, Port Complex, Gear Group, and Condition (aka "Live"). I do these expansions in CALCOM (now with help from Nick Grunloh) as part of the California Collaborative Groundfish Survey, and am happy to help explain the expansion process. Once the expansions are done, the estimated species compositions are sent to PacFIN as the official repository of catch estimates.

If samples are not present for a given quarter, data from other quarters in the same year are "borrowed" in a pre-determined order. Likewise, if samples from a port complex are not available, we borrow from up to 2 port complexes away, but do not borrow across Point Conception. We do not (currently) borrow across years, but have done so using statistical models. As a rule, we do not borrow species comps across market categories, gear groups, or condition (live/dead). If you want to recreate the original estimates, you need to use the same port complexes and gear groups that we used in CALCOM, otherwise you may see differences between PacFIN and CALCOM as a result of comparing estimates with different strata definitions.

**Comment by brianlangseth-NOAA** [comment]
Just visualizing catch at this point. Hence, looking at where catch is occurring. Ive used regular county codes in the past, but melissa pointed out that while that can be ok, may be better to look at port complexes because that is what is used for expanding out catch comps. 

My specific question is what port field within pacfin corresponds to the field catch expansions are calculated from within calcom? Pacfin has two that look reasonable: IOPAC_PORT_GROUP versus PACFIN_GROUP_PORT_CODE. If you dont know @melissamonk-NOAA and I can cross reference

**Comment by EJDick-NOAA** [comment]
Gotcha. I don't know, and I would cross-reference both port complexes and gear groups. I have a hunch there is no exact match in either case, but that is something we need to add to PacFIN -- port and gear definitions that match CALCOM. That would help avoid misunderstandings when people compare CALCOM (the source of the species comp estimates) to PacFIN (the repository). If only we had more people/time....

**Comment by brianlangseth-NOAA** [comment]
@melissamonk-NOAA and I discussed and agreed that IOPAC_PORT_GROUP is NOT the way to go. Using PACFIN_GROUP_PORT_CODE.
